Add files via upload

diff --git a/InstallMgr b/InstallMgr
--- a/InstallMgr
+++ b/InstallMgr
@@ -2,55 +2,59 @@
 
 SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 LISTS_DIR="$SCRIPTS_DIR/Lists"
-ZZ_BIN="/usr/scripts/bin/7zz"
+cd $SCRIPTS_DIR
+ZZ_BIN="../bin/7zz"
 
-if [ "$(whoami)" != "root" ]; then
-  echo "You have to run as Superuser!"
-  exit 1
-fi
-
-for cmd in wget curl rm "$ZZ_BIN"; do
+for cmd in wget curl exit rm chmod while cp  "$ZZ_BIN"; do
   if ! command -v "$cmd" &> /dev/null; then
-    echo "$cmd is missing!"
+    echo -e "\e[31mE: $cmd Is Not Installed.\e[0m"
     exit 1
   fi
 done
 
+if [ "$(whoami)" != "root" ]; then
+    echo -e "\e[31mE: You have to run as Superuser\e[0m"
+    exit 1
+fi
+
 if [ ! -d "$LISTS_DIR" ]; then
-  echo "E: Lists directory $LISTS_DIR does not exist."
+  echo -e "\e[31mE: Lists directory $LISTS_DIR does not exist.\e[0m"
   exit 1
 fi
 
 for list_file in "$LISTS_DIR"/*.list; do
     if [[ -f "$list_file" ]]; then
         if [[ ! -s "$list_file" ]]; then
-            echo "E: List file $list_file is empty."
+            echo -e "\e[31mE: List file $list_file is empty.\e[0m"
+            exit 1
             continue
         fi
         while IFS= read -r line; do
             if [[ $line == Install=* ]]; then
                 url="${line#Install=}"
-                if curl -s -o "$SCRIPTS_DIR/Mgr.sh" "$url"; then
-                    if bash "$SCRIPTS_DIR/Mgr.sh" "$1"; then
-                        echo "Extracting Setup Package..."
-                        if $ZZ_BIN x "$SCRIPTS_DIR/Downloads/Setup.zip" -o"$SCRIPTS_DIR/Setup" > /dev/null; then
-                            if "$SCRIPTS_DIR/Setup/Setup.sh"; then
-                                cp "$SCRIPTS_DIR/Setup/Remove.sh" "$SCRIPTS_DIR/Remove/$1" && chmod +x "$SCRIPTS_DIR/Remove/$1"
-                            else
-                                echo "E: Setup Package failed."
-                            fi
-                        else
-                            echo "E: Failed to Extract Setup Package."
-                        fi
-                    fi
-                fi
-                # Cleanup
-                rm -rf "$SCRIPTS_DIR/Mgr.sh"
-                rm -rf "$SCRIPTS_DIR/Setup"
-                rm -rf "$SCRIPTS_DIR/Downloads/Setup.zip"
             fi
         done < "$list_file"
     else
-        echo "E: No List Files Found in $LISTS_DIR."
+        echo -e "\e[31mE: No List Files Found in $LISTS_DIR.\e[0m"
+        exit 1
     fi
 done
+
+if ! curl -sSL "$url" | bash -s "$1"; then
+    exit 1
+fi
+
+if $ZZ_BIN x "$SCRIPTS_DIR/Downloads/Setup.zip" -o"$SCRIPTS_DIR/Setup" > /dev/null; then
+    if "$SCRIPTS_DIR/Setup/Setup.sh"; then
+        cp "$SCRIPTS_DIR/Setup/Remove.sh" "$SCRIPTS_DIR/Remove/$1"
+    else
+        echo -e "\e[31mE: Setup Package failed.\e[0m"
+        exit 1
+    fi
+else
+    echo -e "\e[31mE: Failed to Extract Setup Package.\e[0m"
+    rm -rf "$SCRIPTS_DIR/Setup" "$SCRIPTS_DIR/Downloads/Setup.zip"
+    exit 1
+fi
+
+rm -rf "$SCRIPTS_DIR/Setup" "$SCRIPTS_DIR/Downloads/Setup.zip"
diff --git a/RemoveMgr b/RemoveMgr
--- a/RemoveMgr
+++ b/RemoveMgr
@@ -1,21 +1,49 @@
 #!/bin/bash
 
 SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-LISTS_DIR="$SCRIPTS_DIR/Lists"
+InstallLists_DIR=$SCRIPTS_DIR/InstallLists
 
-if [ "$(whoami)" != "root" ]
-then
-  echo "You have to run as Superuser!"
-  exit 1
-fi
-
-for cmd in rm; do
+for cmd in rm case chmod for if; do
   if ! command -v "$cmd" &> /dev/null; then
-    echo "$cmd is missing!"
+    echo -e "\e[31mE: $cmd Is Not Installed.\e[0m"
     exit 1
   fi
 done
 
-$SCRIPTS_DIR/Remove/$1
-rm -rf "$SCRIPTS_DIR/Remove/$1"
-rm -rf "$SCRIPTS_DIR/InstallLists/$1.list"
+case "$1" in
+    -l)
+        echo -e "\e[31mLists\e[0m"
+        for list_file in "$InstallLists_DIR"/*.list; do
+             if [[ -f "$list_file" ]]; then
+                 if [[ ! -s "$list_file" ]]; then
+                     echo -e "\e[31mE: List file $list_file is empty.\e[0m"
+                     exit 1
+                     continue
+                 fi
+                 while IFS= read -r line; do
+                     if [[ $line == COMMAND_NAME=* ]]; then
+                         COMMAND_NAMES="${line#COMMAND_NAME=}"
+                         echo -e "\e[1;34m$COMMAND_NAMES\e[0m"
+                     fi
+                 done < "$list_file"
+             else
+                 echo -e "\e[31mE: No List Files Found in InstallLists.\e[0m"
+                 exit 1
+             fi
+        done
+        ;;
+    *)
+        if [ "$(whoami)" != "root" ]; then
+            echo -e "\e[31mE: You have to run as Superuser\e[0m"
+            exit 1
+        fi
+        if ! command -v $SCRIPTS_DIR/Remove/$1 &> /dev/null; then
+            echo -e "\e[31mE: Unable to Locate Package $1\e[0m"
+            exit 1
+        else
+            chmod +x "$SCRIPTS_DIR/Remove/$1"
+            $SCRIPTS_DIR/Remove/$1
+            rm -rf "$SCRIPTS_DIR/Remove/$1" "$SCRIPTS_DIR/InstallLists/$1.list"
+        fi
+        ;;
+esac
diff --git a/UpdateMgr b/UpdateMgr
--- a/UpdateMgr
+++ b/UpdateMgr
@@ -2,21 +2,21 @@
 
 SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 INSTALL_LISTS_DIR="$SCRIPTS_DIR/InstallLists"
-ZZ_BIN="/usr/scripts/bin/7zz"
-
-# Check if the script is run as root
-if [ "$(whoami)" != "root" ]; then
-    echo "You have to run as Superuser!"
-    exit 1
-fi
+cd $SCRIPTS_DIR
+ZZ_BIN="../bin/7zz"
 
 # Check for required commands
-for cmd in chmod curl "$ZZ_BIN"; do
+for cmd in chmod curl "$ZZ_BIN" shopt echo while case exit; do
     if ! command -v "$cmd" &> /dev/null; then
-        echo "$cmd is missing!"
+        echo -e "\e[31mE: $cmd Is Not Installed.\e[0m"
         exit 1
     fi
 done
+
+if [ "$(whoami)" != "root" ]; then
+    echo -e "\e[31mE: You Have To Run As Superuser\e[0m"
+    exit 1
+fi
 
 case "$1" in
     -f)
@@ -25,13 +25,13 @@ case "$1" in
         list_files=("$INSTALL_LISTS_DIR"/*.list)
 
         if [[ ${#list_files[@]} -eq 0 ]]; then
-            echo "E: No List Files Found in $INSTALL_LISTS_DIR."
+            echo -e "\e[31mE: No List Files Found in $INSTALL_LISTS_DIR.\e[0m"
             exit 1
         fi
 
         for list_file in "${list_files[@]}"; do
             if [[ ! -s "$list_file" ]]; then
-                echo "E: List file $list_file is empty."
+                echo -e "\e[31mE: No List Files Found in $INSTALL_LISTS_DIR.\e[0m"
                 continue
             fi
 
@@ -57,11 +57,11 @@ case "$1" in
             if [[ -n "$LATEST_INSTALL_FILE" ]]; then
                 LATEST_COMMAND_FILE=$($LATEST_INSTALL_FILE)
                 if [[ $? -ne 0 ]]; then
-                    echo "E: Failed to fetch latest version for $COMMAND_NAME_FILE."
+                    echo -e "\e[31mE: Failed To Fetch Latest Version For $COMMAND_NAME_FILE.\e[0m"
                     continue
                 fi
             else
-                echo "E: LATEST_VERSION not specified for $COMMAND_NAME_FILE."
+                echo -e "\e[31mE: LATEST_VERSION Not Specified For $COMMAND_NAME_FILE.\e[0m"
                 continue
             fi
 
@@ -69,10 +69,10 @@ case "$1" in
             if [[ "$INSTALL_FILE" < "$LATEST_COMMAND_FILE" ]]; then
                 echo "Installing $COMMAND_NAME_FILE..."
                 if ! $SCRIPTS_DIR/InstallMgr $COMMAND_NAME_FILE; then
-                    echo "E: Failed to install $COMMAND_NAME_FILE."
+                    echo -e "\e[31mE: Failed to Install $COMMAND_NAME_FILE.\e[0m"
                 fi
             else
-                echo "You are already using the latest version of $COMMAND_NAME_FILE: $INSTALL_FILE"
+                echo "You Are Already Using The Latest Version Of $COMMAND_NAME_FILE: $INSTALL_FILE"
             fi
         done
         ;;
@@ -82,13 +82,13 @@ case "$1" in
         list_files=("$INSTALL_LISTS_DIR"/$1.list)
 
         if [[ ${#list_files[@]} -eq 0 ]]; then
-            echo "E: No List Files Found in $INSTALL_LISTS_DIR."
+            echo -e "\e[31mE: No List Files Found in $INSTALL_LISTS_DIR.\e[0m"
             exit 1
         fi
 
         for list_file in "${list_files[@]}"; do
             if [[ ! -s "$list_file" ]]; then
-                echo "E: List file $list_file is empty."
+                echo -e "\e[31mE: No List Files Found in $INSTALL_LISTS_DIR.\e[0m"
                 continue
             fi
 
@@ -114,22 +114,22 @@ case "$1" in
             if [[ -n "$LATEST_INSTALL_FILE" ]]; then
                 LATEST_COMMAND_FILE=$($LATEST_INSTALL_FILE)
                 if [[ $? -ne 0 ]]; then
-                    echo "E: Failed to fetch latest version for $COMMAND_NAME_FILE."
+                    echo -e "\e[31mE: Failed To Fetch Latest Version For $COMMAND_NAME_FILE.\e[0m"
                     continue
                 fi
             else
-                echo "E: LATEST_VERSION not specified for $COMMAND_NAME_FILE."
+                echo -e "\e[31mE: LATEST_VERSION Not Specified For $COMMAND_NAME_FILE.\e[0m"
                 continue
             fi
 
             # Compare versions and decide on installation
             if [[ "$INSTALL_FILE" < "$LATEST_COMMAND_FILE" ]]; then
-                echo "Installing $COMMAND_NAME_FILE..."
-                if ! $SCRIPTS_DIR/InstallMgr $COMMAND_NAME_FILE; then
-                    echo "E: Failed to install $COMMAND_NAME_FILE."
+                if ! spt install $COMMAND_NAME_FILE; then
+                    echo -e "\e[31mE: Failed To Install $COMMAND_NAME_FILE.\e[0m"
+                    rm -rf "$SCRIPTS_DIR/Setup" "$SCRIPTS_DIR/Downloads/Setup.zip"
                 fi
             else
-                echo "You are already using the latest version of $COMMAND_NAME_FILE: $INSTALL_FILE"
+                echo "You Are Already Using The Latest Version Of $COMMAND_NAME_FILE: $INSTALL_FILE"
             fi
         done
         exit 1
